// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNKTKZRGHTGtz39_Mv9YvRW7JC924TX38',
    appId: '1:389216536196:web:3168354fd9ea0f696324d1',
    messagingSenderId: '389216536196',
    projectId: 'mymessanger-6a85f',
    authDomain: 'mymessanger-6a85f.firebaseapp.com',
    databaseURL: 'https://mymessanger-6a85f-default-rtdb.firebaseio.com',
    storageBucket: 'mymessanger-6a85f.appspot.com',
    measurementId: 'G-8WQ7K4NS7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-hMKyDgvG9I5juRWiNixcrzK6F7Zk9s',
    appId: '1:389216536196:android:c77663ef7d44cdab6324d1',
    messagingSenderId: '389216536196',
    projectId: 'mymessanger-6a85f',
    databaseURL: 'https://mymessanger-6a85f-default-rtdb.firebaseio.com',
    storageBucket: 'mymessanger-6a85f.appspot.com',
  );

}